{{- if not .Values.gitWebhookProxy.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.gitWebhookProxy.namespace }}
  labels:
{{ include "gitwebhookproxy.labels.stakater" . | indent 4 }}
{{ include "gitwebhookproxy.labels.chart" . | indent 4 }}
{{- if .Values.gitWebhookProxy.useCustomName }}
  name: {{ .Values.gitWebhookProxy.customName }}
{{- else }}
  name: {{ template "gitwebhookproxy.name" . }}
{{- end }}
data:
    secret: "{{ .Values.gitWebhookProxy.config.secret | b64enc }}"
{{- end }}
