apiVersion: v1
kind: Secret
metadata:
  name: gitwebhookproxy-tls
  namespace: {{ .Values.gitWebhookProxy.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.gitWebhookProxy.tlsSecret.tls_crt }}
  tls.key: {{ .Values.gitWebhookProxy.tlsSecret.tls_key }}